plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
remote_theme: pages-themes/minimal@v0.2.0
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

title: [Phrbmr Hub]
description: [Personal webpage to showcase studies, projects and skills.]


